import { Config } from "effect"
import { InstallationChannel } from "../installation/version"

function getEnv(key: string): string | undefined {
  return process.env[key]
}

function truthy(key: string) {
  const value = getEnv(key)?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = getEnv(key)?.toLowerCase()
  return value === "false" || value === "0"
}

const UNSTABLE_CHANNELS = new Set(["dev", "beta", "local"])
function unstableDefault(key: string) {
  return truthy(key) || (!falsy(key) && UNSTABLE_CHANNELS.has(InstallationChannel))
}

function number(key: string) {
  const value = getEnv(key)
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const CYPHER_EXPERIMENTAL = truthy("CYPHER_EXPERIMENTAL")
const CYPHER_DISABLE_CLAUDE_CODE = truthy("CYPHER_DISABLE_CLAUDE_CODE")
const CYPHER_DISABLE_CLAUDE_CODE_SKILLS = CYPHER_DISABLE_CLAUDE_CODE || truthy("CYPHER_DISABLE_CLAUDE_CODE_SKILLS")
const copy = getEnv("CYPHER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")

function enabledByExperimental(key: string) {
  return getEnv(key) === undefined ? CYPHER_EXPERIMENTAL : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  CYPHER_AUTO_SHARE: truthy("CYPHER_AUTO_SHARE"),
  CYPHER_AUTO_HEAP_SNAPSHOT: truthy("CYPHER_AUTO_HEAP_SNAPSHOT"),
  CYPHER_GIT_BASH_PATH: getEnv("CYPHER_GIT_BASH_PATH"),
  CYPHER_CONFIG: getEnv("CYPHER_CONFIG"),
  CYPHER_CONFIG_CONTENT: getEnv("CYPHER_CONFIG_CONTENT"),
  CYPHER_DISABLE_AUTOUPDATE: truthy("CYPHER_DISABLE_AUTOUPDATE"),
  CYPHER_ALWAYS_NOTIFY_UPDATE: truthy("CYPHER_ALWAYS_NOTIFY_UPDATE"),
  CYPHER_DISABLE_PRUNE: truthy("CYPHER_DISABLE_PRUNE"),
  CYPHER_DISABLE_TERMINAL_TITLE: truthy("CYPHER_DISABLE_TERMINAL_TITLE"),
  CYPHER_SHOW_TTFD: truthy("CYPHER_SHOW_TTFD"),
  CYPHER_DISABLE_DEFAULT_PLUGINS: truthy("CYPHER_DISABLE_DEFAULT_PLUGINS"),
  CYPHER_DISABLE_LSP_DOWNLOAD: truthy("CYPHER_DISABLE_LSP_DOWNLOAD"),
  CYPHER_ENABLE_EXPERIMENTAL_MODELS: truthy("CYPHER_ENABLE_EXPERIMENTAL_MODELS"),
  CYPHER_DISABLE_AUTOCOMPACT: truthy("CYPHER_DISABLE_AUTOCOMPACT"),
  CYPHER_DISABLE_MODELS_FETCH: truthy("CYPHER_DISABLE_MODELS_FETCH"),
  CYPHER_DISABLE_MOUSE: truthy("CYPHER_DISABLE_MOUSE"),
  CYPHER_DISABLE_CLAUDE_CODE,
  CYPHER_DISABLE_CLAUDE_CODE_PROMPT: CYPHER_DISABLE_CLAUDE_CODE || truthy("CYPHER_DISABLE_CLAUDE_CODE_PROMPT"),
  CYPHER_DISABLE_CLAUDE_CODE_SKILLS,
  CYPHER_DISABLE_EXTERNAL_SKILLS: truthy("CYPHER_DISABLE_EXTERNAL_SKILLS"),
  CYPHER_EXPERIMENTAL_CUSTOMIZE_SKILL: unstableDefault("CYPHER_EXPERIMENTAL_CUSTOMIZE_SKILL"),
  CYPHER_FAKE_VCS: getEnv("CYPHER_FAKE_VCS"),
  CYPHER_SERVER_PASSWORD: getEnv("CYPHER_SERVER_PASSWORD"),
  CYPHER_SERVER_USERNAME: getEnv("CYPHER_SERVER_USERNAME"),
  CYPHER_ENABLE_QUESTION_TOOL: truthy("CYPHER_ENABLE_QUESTION_TOOL"),

  CYPHER_EXPERIMENTAL,
  CYPHER_EXPERIMENTAL_FILEWATCHER: Config.boolean("CYPHER_EXPERIMENTAL_FILEWATCHER")
    .pipe(Config.orElse(() => Config.boolean("CYPHER_EXPERIMENTAL_FILEWATCHER")))
    .pipe(Config.withDefault(false)),
  CYPHER_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("CYPHER_EXPERIMENTAL_DISABLE_FILEWATCHER")
    .pipe(Config.orElse(() => Config.boolean("CYPHER_EXPERIMENTAL_DISABLE_FILEWATCHER")))
    .pipe(Config.withDefault(false)),
  CYPHER_EXPERIMENTAL_ICON_DISCOVERY: CYPHER_EXPERIMENTAL || truthy("CYPHER_EXPERIMENTAL_ICON_DISCOVERY"),
  CYPHER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("CYPHER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  CYPHER_ENABLE_EXA: truthy("CYPHER_ENABLE_EXA") || CYPHER_EXPERIMENTAL || truthy("CYPHER_EXPERIMENTAL_EXA"),
  CYPHER_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("CYPHER_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  CYPHER_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("CYPHER_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  CYPHER_EXPERIMENTAL_OXFMT: CYPHER_EXPERIMENTAL || truthy("CYPHER_EXPERIMENTAL_OXFMT"),
  CYPHER_EXPERIMENTAL_LSP_TY: truthy("CYPHER_EXPERIMENTAL_LSP_TY"),
  CYPHER_EXPERIMENTAL_LSP_TOOL: CYPHER_EXPERIMENTAL || truthy("CYPHER_EXPERIMENTAL_LSP_TOOL"),
  CYPHER_EXPERIMENTAL_PLAN_MODE: CYPHER_EXPERIMENTAL || truthy("CYPHER_EXPERIMENTAL_PLAN_MODE"),
  CYPHER_EXPERIMENTAL_SCOUT: CYPHER_EXPERIMENTAL || truthy("CYPHER_EXPERIMENTAL_SCOUT"),
  CYPHER_EXPERIMENTAL_MARKDOWN: !falsy("CYPHER_EXPERIMENTAL_MARKDOWN"),
  CYPHER_ENABLE_PARALLEL: truthy("CYPHER_ENABLE_PARALLEL") || truthy("CYPHER_EXPERIMENTAL_PARALLEL"),
  CYPHER_MODELS_URL: getEnv("CYPHER_MODELS_URL"),
  CYPHER_MODELS_PATH: getEnv("CYPHER_MODELS_PATH"),
  CYPHER_DISABLE_EMBEDDED_WEB_UI: truthy("CYPHER_DISABLE_EMBEDDED_WEB_UI"),
  CYPHER_DB: getEnv("CYPHER_DB"),
  CYPHER_DISABLE_CHANNEL_DB: truthy("CYPHER_DISABLE_CHANNEL_DB"),
  CYPHER_SKIP_MIGRATIONS: truthy("CYPHER_SKIP_MIGRATIONS"),
  CYPHER_STRICT_CONFIG_DEPS: truthy("CYPHER_STRICT_CONFIG_DEPS"),

  CYPHER_WORKSPACE_ID: getEnv("CYPHER_WORKSPACE_ID"),
  CYPHER_EXPERIMENTAL_WORKSPACES: enabledByExperimental("CYPHER_EXPERIMENTAL_WORKSPACES"),
  CYPHER_EXPERIMENTAL_EVENT_SYSTEM: CYPHER_EXPERIMENTAL || truthy("CYPHER_EXPERIMENTAL_EVENT_SYSTEM"),
  CYPHER_EXPERIMENTAL_SESSION_SWITCHING: CYPHER_EXPERIMENTAL || truthy("CYPHER_EXPERIMENTAL_SESSION_SWITCHING"),
  CYPHER_EXPERIMENTAL_SESSION_SWITCHER: enabledByExperimental("CYPHER_EXPERIMENTAL_SESSION_SWITCHER"),
  get CYPHER_DISABLE_PROJECT_CONFIG() {
    return truthy("CYPHER_DISABLE_PROJECT_CONFIG")
  },
  get CYPHER_TUI_CONFIG() {
    return getEnv("CYPHER_TUI_CONFIG")
  },
  get CYPHER_CONFIG_DIR() {
    return getEnv("CYPHER_CONFIG_DIR")
  },
  get CYPHER_PURE() {
    return truthy("CYPHER_PURE")
  },
  get CYPHER_PERMISSION() {
    return getEnv("CYPHER_PERMISSION")
  },
  get CYPHER_PLUGIN_META_FILE() {
    return getEnv("CYPHER_PLUGIN_META_FILE")
  },
  get CYPHER_CLIENT() {
    return getEnv("CYPHER_CLIENT") ?? "cli"
  },
  get CYPHER_SESSION_RETRY_LIMIT() {
    return number("CYPHER_SESSION_RETRY_LIMIT")
  },
}
